plot4 <- function()
{
  data <- read.csv("household_power_consumption.txt", sep = ";", header = FALSE,na.strings = "?", skip = 66637, nrows = 2880, colClasses = "character") 
  data$V1 <- strptime(paste(data[,1],data[,2]),format = "%d/%m/%Y %H:%M:%S")
  names(data) <- c("Date","Time", "Global_active_power", "Global_reactive_power","Voltage", "Global_intensity", "Sub_metering_1","Sub_metering_2", "Sub_metering_3")
  data$Global_active_power <- as.numeric(data$Global_active_power)  
  png(file = "plot4.png",width = 480, height = 480)
  Sys.setlocale("LC_TIME", "English") # because otherwise I get dutch tick marks
  par(mfrow = c(2,2))
  par(lwd = 1)
  with(data, plot(Date, Global_active_power, type = "n", xlab ="",ylab = "Global Active Power"))
  lines(data$Date, data$Global_active_power)
  with(data, plot(x = Date, y = Voltage, type = "n", xlab = "datetime"))
  lines(data$Date, data$Voltage)  
  with(data, plot(Date, Sub_metering_1, type = "n", xlab ="",ylab = "Energy sub metering"))
  lines(x = data$Date, y = data$Sub_metering_1, col = "black")
  lines(x = data$Date, y = data$Sub_metering_2, col = "red")
  lines(x = data$Date, y = data$Sub_metering_3, col = "blue")
  legend("topright", legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), lty = c(1,1), col = c("black","red", "blue"), bty = "n")
  with(data, plot(Date, Global_reactive_power, type = "n", xlab ="datetime"))
  lines(data$Date, data$Global_reactive_power)
  dev.off()
}